"""Guest user role

Revision ID: 440d28a6c17c
Revises: 6c639807d7f5
Create Date: 2026-09-16 12:49:58.114334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '440d28a6c17c'
down_revision: Union[str, Sequence[str], None] = '6c639807d7f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE user_role_enum AS ENUM ('ADMIN', 'USER');")
    op.add_column('users', sa.Column('user_role', sa.Enum('ADMIN', 'USER', name='user_role_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_role')
    # ### end Alembic commands ###
