"""Revoke reason

Revision ID: d292be9b5dbb
Revises: 7eaf0b63fc67
Create Date: 2026-09-30 13:25:44.874806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd292be9b5dbb'
down_revision: Union[str, Sequence[str], None] = '7eaf0b63fc67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE revoke_reason_enum AS ENUM('ROTATED', 'USER_LOGOUT', 'FORCE_LOGOUT')")
    op.add_column('refresh_tokens', sa.Column('revoke_reason', sa.Enum('ROTATED', 'USER_LOGOUT', 'FORCE_LOGOUT', name='revoke_reason_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'revoke_reason')
    op.execute("DROP TYPE IF EXISTS revoke_reason_enum")
    # ### end Alembic commands ###
