"""Revoke reason

Revision ID: e2575c6d076e
Revises: 7eaf0b63fc67
Create Date: 2026-09-30 11:36:06.464370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2575c6d076e'
down_revision: Union[str, Sequence[str], None] = '7eaf0b63fc67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE revoke_reason_enum AS ENUM('ROTATED', 'LOGOUT')")
    op.add_column('refresh_tokens', sa.Column('revoke_reason', sa.Enum('ROTATED', 'LOGOUT', name='revoke_reason_enum'), nullable=True))
    op.create_unique_constraint(None, 'refresh_tokens', ['token_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_column('refresh_tokens', 'revoke_reason')
    op.execute("DROP TYPE IF EXISTS revoke_reason_enum")
    # ### end Alembic commands ###
